[program:guess-three]
command=/var/www/guess-three/api
directory=/var/www/guess-three
user=www-data
autostart=true
autorestart=true
startsecs=10
startretries=3
stdout_logfile=/var/log/guess-three/guess-api.log
stderr_logfile=/var/log/guess-three/guess-api-error.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
environment=PORT=8786,GO_ENV=production
priority=999
stopsignal=TERM
stopwaitsecs=30